In [1]:
#importing library
import numpy as np
import pandas as pd

**DataFrames**

In [2]:
#lists of data
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [3]:
#to access a DataFrame
df = pd.DataFrame(data, columns=columns)
print(df)

      Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC
2    Lotus     Elise  2010      218.0                 4            MANUAL
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC
4   Nissan  Frontier  2017      261.0                 6            MANUAL

  Vehicle_Style   MSRP
0         sedan   2000
1         Sedan  27150
2   convertible  54990
3       4dr SUV  34450
4        Pickup  32340

In [4]:
#to access first two rows
df.head(2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

**Series**

In [5]:
#to access a particular column by dot notation
df.Year

0    1991
1    2017
2    2010
3    2017
4    2017
Name: Year, dtype: int64

In [6]:
#to access a particular column using square brackets
df['Transmission Type']

0       MANUAL
1    AUTOMATIC
2       MANUAL
3    AUTOMATIC
4       MANUAL
Name: Transmission Type, dtype: str

In [7]:
#to access multiple columns
df[['Year', 'MSRP', 'Engine Cylinders']]

   Year   MSRP  Engine Cylinders
0  1991   2000                 4
1  2017  27150                 4
2  2010  54990                 4
3  2017  34450                 4
4  2017  32340                 6

In [8]:
#to add a column
df['id'] = [1, 2, 3, 4, 5]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [9]:
#to delete a column
del df['id']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

**Index**

In [10]:
#to access indexes
df.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
#access element by there location
df.loc[2]

Make                       Lotus
Model                      Elise
Year                        2010
Engine HP                  218.0
Engine Cylinders               4
Transmission Type         MANUAL
Vehicle_Style        convertible
MSRP                       54990
Name: 2, dtype: object

In [13]:
#to change the indexing
df.index = ['a', 'b', 'c', 'd', 'e']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [14]:
#to access the element by their index
df.iloc[[0, 3]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [15]:
#to reset the index
df = df.reset_index(drop=True)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

**Element wise operation**

In [16]:
#multiplication
df['Year'] * 2

0    3982
1    4034
2    4020
3    4034
4    4034
Name: Year, dtype: int64

In [17]:
#comparision
df['Year'] >= 2025

0    False
1    False
2    False
3    False
4    False
Name: Year, dtype: bool

**Filtering**

In [20]:
df[
    df['Year'] >= 2010
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [21]:
#to combine conditions
df[
    (df['Year'] >= 2010) & (df['Make'] == 'Nissan')
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

**String**

In [22]:
#to make every word in lowercase
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [24]:
#replacing all spaces with underscore
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_').str.lower()
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

**Summarizing operators**

In [28]:
df.MSRP.mean()

np.float64(30186.0)

In [29]:
df.MSRP.max()

np.int64(54990)

In [30]:
#to get all the statitics at once
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [31]:
#to get number of unique values
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [32]:
#to get unique values in a specific column
df.Model.nunique()

5

**Missing Values**

In [33]:
#to find number of missing values
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

**GroupBy**

In [35]:
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

**Getting Numpy array from DataFrame**

In [36]:
df.Year.values

array([1991, 2017, 2010, 2017, 2017])

**Getting Dictionaries From DataFrames**

In [38]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]